#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ALU.sv --exe ALU_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VALU.mk VALU

# run executable simulation file
obj_dir/VALU

